name: Lambda CI - ZIP 

on:
  push:
    branches:
      - main
    paths:
      - 'backend/lambda_functions/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Build zip files for each lambda function
        run: |
          cd backend/lambda_functions
          for d in */ ; do
            zip -r "${d%/}.zip" "$d"
          done

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Upload zip files to S3
      #   run: |
      #     aws s3 cp . s3://my-bucket-name/lambda_functions/ --recursive --exclude "*" --include "*.zip"
      #   working-directory: backend/lambda_functions
